const prisma = require('../config/prisma');
const crypto = require('crypto');
const { withLegacyId, withLegacyIds } = require('../utils/prismaResponse');

const PROVIDER_PROFILE_FIELDS = new Set([
  'activePlanId', 'activeSubscriptionId', 'activityLogs', 'aiGeneratedDraft',
  'aiSuggestions', 'allowedCitiesCount', 'allowedPincodesCount',
  'allowedSkillsCount', 'approvalAction', 'approvalNote', 'approvalSections',
  'approvedAt', 'approvedBy', 'approvedByRole', 'availability',
  'availabilitySummary', 'boostWeight', 'boostedUntil', 'category', 'city',
  'company', 'contactVisibility', 'contactsUnlocked', 'currentCtc',
  'currentPlan', 'customConfig', 'description', 'designation', 'documents',
  'education', 'embedding', 'embeddingText', 'expandedSkills', 'expectedCtc',
  'experience', 'finalBio', 'followBackRequest', 'freelancerAnalytics',
  'geoPoint', 'inRotationPool', 'isActiveSubscription', 'isApproved',
  'isPublicProfile', 'isResumeAutoGenerated', 'isTopCity', 'isTopInCity',
  'isTopInCountry', 'isTopInPincode', 'isVerified', 'jobType',
  'languageEntries', 'languages', 'lastAnalyzedHash', 'lastShownAt',
  'latitude', 'leadsReceived', 'location', 'locationData', 'locationUpdatedAt',
  'locations', 'longitude', 'nearestLocation', 'noticePeriod', 'originalBio',
  'originalPortfolioLinks', 'originalSkills', 'parsedResumeData', 'photo',
  'planBenefitsSnapshot', 'planCoverageType', 'planExpiresAt', 'portfolioLinks',
  'preferredCountries', 'previousExperience', 'pricing', 'pricingEntries',
  'pricingType', 'priorityWeight', 'profileCompletion', 'profileExpiresAt',
  'profileName', 'profilePhoto', 'profilePhotoApproval', 'profileStatus',
  'profileViews', 'projects', 'rankingScore', 'rating', 'relocationAvailable',
  'remoteAvailable', 'renewalReminderSent', 'resumeApproval', 'resumeParsing',
  'resumeUrl', 'roles', 'serviceLocationData', 'serviceLocations', 'skillLevel',
  'skills', 'specialities', 'state', 'subscriptionEndDate', 'subscriptionPlan',
  'subscriptionStartDate', 'tier', 'totalReviews', 'trustScore',
  'uploadedAssets', 'user', 'visibility', 'visibilityLevel', 'whatsappAlerts',
  'whatsappConsent', 'whatsappFreelancePlanActive',
  'whatsappFreelancePlanExpiry', 'whatsappFreelancePlanSubscriptionId',
  'willingToTravelKm', 'workMode',
  'professionalTitle', 'headlineSkill', 'keyAchievement',
  'preferredProjectDuration', 'workHours', 'whatsappAvailability',
  'contactConsent', 'contactMediums', 'voiceIntroUrl', 'videoIntroUrl',
  'idVerification',
]);

const JSON_FIELDS = new Set([
  'activityLogs', 'aiGeneratedDraft', 'aiSuggestions', 'approvalSections',
  'availabilitySummary', 'customConfig', 'education', 'embedding',
  'followBackRequest', 'freelancerAnalytics', 'geoPoint', 'languageEntries',
  'location', 'locationData', 'originalPortfolioLinks', 'parsedResumeData',
  'planBenefitsSnapshot', 'portfolioLinks', 'previousExperience',
  'pricingEntries', 'profilePhotoApproval', 'projects', 'resumeApproval',
  'resumeParsing', 'serviceLocationData', 'serviceLocations', 'specialities',
  'uploadedAssets', 'workHours', 'whatsappAvailability', 'idVerification',
]);

const DATE_FIELDS = new Set([
  'approvedAt', 'boostedUntil', 'lastShownAt', 'locationUpdatedAt',
  'planExpiresAt', 'profileExpiresAt', 'subscriptionEndDate',
  'subscriptionStartDate', 'whatsappFreelancePlanExpiry',
]);

const toJsonCompatible = (value) => {
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(toJsonCompatible);
  if (value && typeof value === 'object') {
    if (value.constructor && value.constructor !== Object && typeof value.toString === 'function') {
      return value.toString();
    }
    return Object.fromEntries(
      Object.entries(value)
        .filter(([, nested]) => nested !== undefined)
        .map(([key, nested]) => [key, toJsonCompatible(nested)]),
    );
  }
  return value;
};

function prepareProviderProfileData(source) {
  const data = {};
  for (const [key, value] of Object.entries(source || {})) {
    if (PROVIDER_PROFILE_FIELDS.has(key) && value !== undefined) data[key] = value;
  }
  if (data.user != null) data.user = String(data.user);
  for (const field of ['approvedBy', 'activePlanId', 'activeSubscriptionId']) {
    if (data[field] != null) data[field] = String(data[field]);
  }
  for (const field of DATE_FIELDS) {
    if (typeof data[field] === 'number') data[field] = new Date(data[field]);
  }
  for (const field of ['city', 'state', 'nearestLocation']) {
    if (typeof data[field] === 'string') data[field] = data[field].trim();
  }
  if (Array.isArray(data.portfolioLinks)) {
    data.portfolioLinks = data.portfolioLinks.map((link) => ({
      ...link,
      _id: String(link?._id || link?.id || crypto.randomUUID()),
    }));
  }

  const latitude = Number(data.location?.latitude ?? data.locationData?.latitude ?? data.latitude);
  const longitude = Number(data.location?.longitude ?? data.locationData?.longitude ?? data.longitude);
  if (Number.isFinite(latitude) && latitude >= -90 && latitude <= 90
    && Number.isFinite(longitude) && longitude >= -180 && longitude <= 180) {
    data.geoPoint = { type: 'Point', coordinates: [longitude, latitude] };
  }
  for (const field of JSON_FIELDS) {
    if (data[field] != null) data[field] = toJsonCompatible(data[field]);
  }
  return data;
}

function mapProviderRecord(record) {
  if (!record) return record;
  const { userRecord, approvedByRecord, ...profile } = record;
  return {
    ...withLegacyId(profile),
    ...(userRecord !== undefined ? { user: withLegacyId(userRecord) } : {}),
    ...(approvedByRecord !== undefined ? { approvedBy: withLegacyId(approvedByRecord) } : {}),
  };
}

const relationInclude = (userSelect) => userSelect
  ? { userRecord: { select: userSelect } }
  : undefined;

async function findProviderProfileByUserId(userId, { userSelect } = {}) {
  return mapProviderRecord(await prisma.providerProfile.findUnique({
    where: { user: String(userId) },
    ...(userSelect ? { include: relationInclude(userSelect) } : {}),
  }));
}

async function findProviderProfileByIdOrUserId(value, { userSelect } = {}) {
  const include = userSelect ? relationInclude(userSelect) : undefined;
  const id = String(value);
  let record = await prisma.providerProfile.findUnique({
    where: { id },
    ...(include ? { include } : {}),
  });
  if (!record) {
    record = await prisma.providerProfile.findUnique({
      where: { user: id },
      ...(include ? { include } : {}),
    });
  }
  return mapProviderRecord(record);
}

async function createProviderProfile(data) {
  return mapProviderRecord(await prisma.providerProfile.create({
    data: prepareProviderProfileData(data),
  }));
}

async function ensureProviderProfile(userId, defaults = {}) {
  const data = prepareProviderProfileData({ ...defaults, user: String(userId) });
  return mapProviderRecord(await prisma.providerProfile.upsert({
    where: { user: String(userId) },
    create: data,
    update: {},
  }));
}

async function saveProviderProfile(profile) {
  return mapProviderRecord(await prisma.providerProfile.update({
    where: { id: String(profile.id || profile._id) },
    data: prepareProviderProfileData(profile),
  }));
}

async function updateProviderProfile(userId, data) {
  return mapProviderRecord(await prisma.providerProfile.update({
    where: { user: String(userId) },
    data: prepareProviderProfileData(data),
  }));
}

async function deleteProviderProfile(userId) {
  return mapProviderRecord(await prisma.providerProfile.delete({
    where: { user: String(userId) },
  }));
}

function calculateProfileCompletion(profile, user = null) {
  const u = user || profile?.userRecord || {};
  const weights = {
    photo: 5,
    name: 4,
    title: 3,
    mobileVerified: 9,
    emailVerified: 5,
    location: 5,
    category: 2,
    experience: 2,
    skills: 12,
    skillProof: 8,
    about: 5,
    achievement: 3,
    eduwork: 8,
    links: 8,
    resume: 6,
    languages: 3,
    availability: 2,
    duration: 2,
    waAvailability: 3,
    consent: 3,
    idVerify: 8,
    voiceIntro: 4,
    videoIntro: 4,
  };

  const details = {
    photo: !!(profile?.photo || profile?.profilePhoto || u?.profilePhoto),
    name: !!((u?.name || profile?.profileName || '').trim()),
    title: !!((profile?.professionalTitle || profile?.designation || '').trim()),
    mobileVerified: !!(u?.isPhoneVerified || profile?.isPhoneVerified),
    emailVerified: !!(u?.isEmailVerified || profile?.isEmailVerified),
    location: !!(profile?.city && profile?.state),
    category: !!((profile?.category || '').trim()),
    experience: !!((profile?.experience || '').trim()),
    skills: Array.isArray(profile?.skills) && profile.skills.length > 0,
    skillProof: Array.isArray(profile?.pricingEntries) && profile.pricingEntries.some((s) => s?.proofLink || s?.proofFile),
    about: !!((profile?.description || '').trim()),
    achievement: !!((profile?.keyAchievement || '').trim()),
    eduwork: (Array.isArray(profile?.education) && profile.education.length > 0) ||
             (Array.isArray(profile?.previousExperience) && profile.previousExperience.length > 0),
    links: Array.isArray(profile?.portfolioLinks) && profile.portfolioLinks.length > 0,
    resume: !!((profile?.resumeUrl || '').trim()),
    languages: (Array.isArray(profile?.languages) && profile.languages.length > 0) ||
               (Array.isArray(profile?.languageEntries) && profile.languageEntries.length > 0),
    availability: !!((profile?.availability || '').trim()),
    duration: !!((profile?.preferredProjectDuration || '').trim()),
    waAvailability: !!(profile?.whatsappAvailability?.enabled || profile?.whatsappAlerts),
    consent: !!(profile?.contactConsent && Array.isArray(profile?.contactMediums) && profile.contactMediums.length > 0),
    idVerify: !!(profile?.idVerification?.enabled || profile?.isVerified),
    voiceIntro: !!((profile?.voiceIntroUrl || '').trim()),
    videoIntro: !!((profile?.videoIntroUrl || '').trim()),
  };

  let rawScore = 0;
  for (const [key, isDone] of Object.entries(details)) {
    if (isDone) rawScore += weights[key] || 0;
  }

  return {
    details,
    percentage: Math.min(100, rawScore),
  };
}

module.exports = {
  calculateProfileCompletion,
  createProviderProfile,
  deleteProviderProfile,
  ensureProviderProfile,
  findProviderProfileByIdOrUserId,
  findProviderProfileByUserId,
  mapProviderRecord,
  prepareProviderProfileData,
  saveProviderProfile,
  updateProviderProfile,
  withProviderId: withLegacyId,
  withProviderIds: withLegacyIds,
};
