const mongoose = require('mongoose');

const jobSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, default: null },
  companyName: { type: String, required: true },
  companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'CompanyMaster', default: null },
  companyDomain: { type: String, default: null },
  locationText: { type: String, required: true },
  city: { type: String, default: null },
  state: { type: String, default: null },
  country: { type: String, default: null },
  canonicalLocationId: { type: mongoose.Schema.Types.ObjectId, ref: 'LocationMaster', default: null },
  jobType: { type: String, default: null },
  employmentType: { type: String, default: null },
  salaryRaw: { type: String, default: null },
  salaryNormalizedAnnual: { type: Number, default: null },
  salaryCurrency: { type: String, default: null },
  salaryMin: { type: Number, default: null },
  salaryMax: { type: Number, default: null },
  salaryUnit: { type: String, default: null },
  postedDate: { type: Date, default: null },
  validThrough: { type: Date, default: null },
  applyUrl: { type: String, required: true },
  sourceApplyUrl: { type: String, default: null },
  sourceJobId: { type: String, default: null },
  requisitionId: { type: String, default: null },
  sourceName: { type: String, default: null },
  sourceType: { type: String, default: null },
  sourceConfidenceScore: { type: Number, default: 0 },
  canonicalSourceVersionId: { type: mongoose.Schema.Types.ObjectId, ref: 'JobSourceVersion', default: null },
  categoryId: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', default: null },
  categoryName: { type: String, default: null },
  status: { type: String, enum: ['active', 'needs_review', 'expired', 'rejected', 'duplicate'], default: 'active' },
  expiryReason: { type: String, default: null },
  missingSuccessfulScanCount: { type: Number, default: 0 },
  lastSeenAt: { type: Date, default: Date.now },
  firstSeenAt: { type: Date, default: Date.now },
  contentFingerprint: { type: String, default: null },
  compositeKey: { type: String, default: null },
  duplicateGroupId: { type: mongoose.Schema.Types.ObjectId, ref: 'DuplicateGroup', default: null },
  validationStatus: { type: String, enum: ['passed', 'failed', 'needs_review'], default: 'needs_review' },
  validationErrors: [{ type: String }]
}, { timestamps: true });

module.exports = mongoose.model('PipelineJob', jobSchema); // Named PipelineJob in Mongoose to avoid Job collision if any
