/* eslint-disable no-console */
// Generates the runtime model modules that route all persistence through Prisma.
// Legacy Mongoose schemas remain isolated in legacy-mongoose-models for audit and
// later data-migration mapping; runtime code must import from models.
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');

const backendRoot = path.resolve(__dirname, '..');
const legacyRoot = path.join(backendRoot, 'legacy-mongoose-models');
const outputRoot = path.join(backendRoot, 'models');

process.env.ENCRYPTION_SECRET ||= 'prisma-model-generation-only';

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(fullPath) : [fullPath];
  });
}

function relativeRequire(fromDirectory, targetFile) {
  let relative = path.relative(fromDirectory, targetFile).replace(/\\/g, '/');
  if (!relative.startsWith('.')) relative = `./${relative}`;
  return relative.replace(/\.js$/, '');
}

let generated = 0;
for (const legacyPath of walk(legacyRoot).filter((file) => file.endsWith('.js')).sort()) {
  const relativePath = path.relative(legacyRoot, legacyPath);
  const outputPath = path.join(outputRoot, relativePath);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  try {
    const exported = require(legacyPath);
    const candidates = exported?.modelName
      ? [exported]
      : Object.values(exported || {}).filter((value) => value?.modelName);

    if (candidates.length === 1) {
      const repositoryPath = relativeRequire(path.dirname(outputPath), path.join(backendRoot, 'repositories', 'prismaModel.js'));
      fs.writeFileSync(
        outputPath,
        `// Generated by scripts/generatePrismaModelFiles.js.\nmodule.exports = require('${repositoryPath}')('${candidates[0].modelName}');\n`,
      );
      generated += 1;
    } else {
      // The only current non-model module contains embedded schema fragments.
      // Prisma stores those fragments as Json, so no runtime schema object is needed.
      fs.writeFileSync(
        outputPath,
        '// Embedded legacy schema fragments are represented by Json fields in Prisma.\nmodule.exports = Object.freeze({});\n',
      );
    }
  } finally {
    mongoose.deleteModel(/.+/);
  }
}

console.log(`Generated ${generated} Prisma-backed model modules in ${path.relative(backendRoot, outputRoot)}`);

