/**
 * seedPlansPrisma.js
 * Production-ready idempotent seed script for Plans using Prisma and PostgreSQL.
 * Populates standard Provider plans (including Default Free Provider Plan)
 * and Recruiter plans.
 */

const dotenv = require('dotenv');
dotenv.config();

const prisma = require('../config/prisma');

const providerPlans = [
  {
    name: 'Default Free Provider Plan',
    slug: 'provider-free-default',
    type: 'provider',
    audience: 'provider',
    planType: 'free',
    price: 0,
    priceMonthly: 0,
    billingCycle: 'yearly',
    gstPercent: 0,
    isDefaultFree: true,
    isProviderDefault: true,
    description: 'Default free plan assigned automatically on provider registration.',
    coverageType: 'pincode',
    maxSkills: 2,
    maxPincodes: 2,
    maxCities: 1,
    maxJobApplications: 5,
    visibilityLevel: 'basic',
    priorityWeight: 0,
    isActive: true,
    status: 'active',
    duration: 365,
    planCategory: 'default_free',
    usageResetCycle: 'monthly',
    features: [
      '2 free locations/pincodes coverage',
      '2 free skills category selection',
      '5 job applications per month',
      'Basic search visibility',
    ],
    sortOrder: 0,
  },
  {
    name: 'Add Multiple Skills',
    slug: 'add-multiple-skills',
    type: 'provider',
    audience: 'provider',
    planType: 'paid',
    price: 300,
    priceMonthly: 300,
    billingCycle: 'monthly',
    gstPercent: 18,
    isDefaultFree: false,
    isProviderDefault: false,
    description: 'Show multiple skills in one pincode.',
    coverageType: 'pincode',
    maxSkills: 10,
    maxPincodes: 1,
    maxCities: 1,
    maxJobApplications: 20,
    visibilityLevel: 'basic',
    priorityWeight: 20,
    allowedSkills: 'multiple',
    allowedPincodes: 1,
    supportsWhatsappAlerts: true,
    supportsSmsAlerts: true,
    supportsPerformanceInsights: true,
    isActive: true,
    status: 'active',
    duration: 30,
    planCategory: 'multiple_skills',
    usageResetCycle: 'monthly',
    features: [
      'Multiple skills (up to 10)',
      '1 pincode coverage',
      '20 job applications per month',
      'Priority in search results',
      'WhatsApp + SMS alerts',
      'Performance insights',
    ],
    sortOrder: 1,
  },
  {
    name: 'One Locality Top',
    slug: 'one-pincode-top',
    type: 'provider',
    audience: 'provider',
    planType: 'paid',
    price: 299,
    priceMonthly: 299,
    discountedPrice: 499,
    billingCycle: 'monthly',
    gstPercent: 18,
    isDefaultFree: false,
    isProviderDefault: false,
    description: 'Top position in selected locality (pincode).',
    coverageType: 'pincode',
    maxSkills: 1,
    maxPincodes: 1,
    maxCities: 1,
    maxJobApplications: 30,
    visibilityLevel: 'pincode_top',
    priorityWeight: 40,
    allowedSkills: 1,
    allowedPincodes: 1,
    supportsWhatsappAlerts: true,
    supportsSmsAlerts: true,
    isActive: true,
    status: 'active',
    duration: 30,
    planCategory: 'locality_top',
    usageResetCycle: 'monthly',
    features: [
      'Top position in selected pincode/locality',
      '1 skill category',
      '30 job applications per month',
      'Priority in search results',
      'More profile views',
      'WhatsApp + SMS alerts',
    ],
    sortOrder: 2,
  },
  {
    name: 'Top in City',
    slug: 'top-in-city',
    type: 'provider',
    audience: 'provider',
    planType: 'paid',
    price: 499,
    priceMonthly: 499,
    discountedPrice: 799,
    billingCycle: 'monthly',
    gstPercent: 18,
    isDefaultFree: false,
    isProviderDefault: false,
    isPopular: true,
    description: 'Top position in entire city.',
    coverageType: 'city',
    maxSkills: 10,
    maxPincodes: 50,
    maxCities: 1,
    maxJobApplications: 50,
    visibilityLevel: 'city_top',
    priorityWeight: 70,
    allowedSkills: 'multiple',
    allowedPincodes: 'all_city',
    allowedCities: 1,
    isActive: true,
    status: 'active',
    duration: 30,
    planCategory: 'city_top',
    usageResetCycle: 'monthly',
    features: [
      'Top position in entire city',
      'Multiple skills (up to 10)',
      'All pincodes in one city',
      '50 job applications per month',
      'Priority in search results',
      'More profile views',
    ],
    sortOrder: 3,
  },
  {
    name: 'Show Top in Country',
    slug: 'show-top-in-country',
    type: 'provider',
    audience: 'provider',
    planType: 'paid',
    price: 2999,
    priceMonthly: 2999,
    discountedPrice: 4999,
    billingCycle: 'monthly',
    gstPercent: 18,
    isDefaultFree: false,
    isProviderDefault: false,
    description: 'Top position across country.',
    coverageType: 'country',
    maxSkills: 20,
    maxPincodes: 1000,
    maxCities: 100,
    maxJobApplications: 100,
    visibilityLevel: 'country_top',
    priorityWeight: 100,
    allowedSkills: 'multiple',
    allowedPincodes: 'country',
    supportsWhatsappAlerts: true,
    supportsSmsAlerts: true,
    isActive: true,
    status: 'active',
    duration: 30,
    planCategory: 'country_top',
    usageResetCycle: 'monthly',
    features: [
      'Top position across country',
      'Multiple skills (up to 20)',
      '100 job applications per month',
      'Highest priority in search',
      'Maximum profile visibility',
      'WhatsApp + SMS alerts',
    ],
    sortOrder: 4,
  },
  {
    name: 'Customise Plan',
    slug: 'customise-plan',
    type: 'provider',
    audience: 'provider',
    planType: 'custom',
    price: 0,
    priceMonthly: 0,
    billingCycle: 'custom',
    gstPercent: 18,
    isDefaultFree: false,
    isProviderDefault: false,
    description: 'Create your own plan as per your need.',
    coverageType: 'custom',
    visibilityLevel: 'custom',
    priorityWeight: 0,
    allowedSkills: 'multiple',
    allowedCities: 'multiple',
    isActive: true,
    status: 'active',
    duration: 30,
    planCategory: 'custom',
    usageResetCycle: 'monthly',
    isCustomisable: true,
    features: [
      'Choose multiple cities',
      'Choose multiple skills',
      'Set visibility level',
      'Flexible duration',
      'Best for businesses',
    ],
    customConfig: {
      allowSkillSelection: true,
      allowCitySelection: true,
      allowPincodeSelection: true,
      allowVisibilitySelection: true,
      allowDurationSelection: true,
      minSkills: 1,
      maxSkills: 15,
      minCities: 1,
      maxCities: 10,
      minPincodes: 1,
      maxPincodes: 50,
      minDurationMonths: 1,
      maxDurationMonths: 12,
    },
    sortOrder: 5,
  },
];

const recruiterPlans = [
  {
    name: 'Free',
    slug: 'free',
    type: 'recruiter',
    audience: 'recruiter',
    planType: 'free',
    price: 0,
    priceMonthly: 0,
    billingCycle: 'monthly',
    duration: 30,
    sortOrder: 1,
    isDefaultFree: true,
    isProviderDefault: false,
    isActive: true,
    status: 'active',
    description: 'For new recruiters',
    features: ['Free job posting forever', 'Unlimited candidate search', 'Basic candidate access'],
    metadata: {
      bestFor: 'First-time recruiters',
    },
  },
  {
    name: 'AI Starter',
    slug: 'ai-starter',
    type: 'recruiter',
    audience: 'recruiter',
    planType: 'paid',
    price: 499,
    priceMonthly: 499,
    billingCycle: 'monthly',
    duration: 30,
    sortOrder: 2,
    isPopular: true,
    isDefaultFree: false,
    isProviderDefault: false,
    isActive: true,
    status: 'active',
    description: 'For startups & small teams',
    features: ['AI tools to find the right talent', 'Promote jobs & boost visibility', 'Automate outreach'],
    metadata: {
      bestFor: 'Startups',
      hireLimitText: 'Hire up to 10 positions/month',
      saveHoursText: 'Save 40+ hours/month',
    },
  },
  {
    name: 'AI Growth',
    slug: 'ai-growth',
    type: 'recruiter',
    audience: 'recruiter',
    planType: 'paid',
    price: 1499,
    priceMonthly: 1499,
    billingCycle: 'monthly',
    duration: 30,
    sortOrder: 3,
    isDefaultFree: false,
    isProviderDefault: false,
    isActive: true,
    status: 'active',
    description: 'For growing companies',
    features: ['Advanced AI hiring tools', 'Get more quality applicants', 'Advanced analytics'],
    metadata: {
      bestFor: 'SMBs',
      hireLimitText: 'Hire up to 50 positions/month',
      saveHoursText: 'Save 120+ hours/month',
    },
  },
  {
    name: 'AI Business',
    slug: 'ai-business',
    type: 'recruiter',
    audience: 'recruiter',
    planType: 'paid',
    price: 4999,
    priceMonthly: 4999,
    billingCycle: 'monthly',
    duration: 30,
    sortOrder: 4,
    isDefaultFree: false,
    isProviderDefault: false,
    isActive: true,
    status: 'active',
    description: 'For agencies & teams',
    features: ['Unlimited everything', 'Advanced automation', 'Priority support'],
    metadata: {
      bestFor: 'Agencies & Large Teams',
      hireLimitText: 'Unlimited hiring',
      saveHoursText: 'Save 300+ hours/month',
    },
  },
  {
    name: 'Enterprise',
    slug: 'enterprise',
    type: 'recruiter',
    audience: 'recruiter',
    planType: 'custom',
    price: 9999,
    priceMonthly: 9999,
    billingCycle: 'monthly',
    duration: 30,
    sortOrder: 5,
    isDefaultFree: false,
    isProviderDefault: false,
    isActive: true,
    status: 'active',
    description: 'For large enterprises',
    features: ['Custom solutions', 'Dedicated support', 'SLA & security'],
    metadata: {
      bestFor: 'Large Enterprises & Recruitment Firms',
    },
  },
];

async function seedPlans() {
  console.log('[seedPlansPrisma] Starting plan seed...');

  const allPlans = [...providerPlans, ...recruiterPlans];

  for (const plan of allPlans) {
    const key = {
      type: plan.type,
      slug: plan.slug,
      duration: plan.duration,
    };

    const record = await prisma.plan.upsert({
      where: {
        type_slug_duration: key,
      },
      update: {
        ...plan,
      },
      create: {
        ...plan,
      },
    });

    console.log(`[seedPlansPrisma] Synced plan: [${record.type}] ${record.name} (${record.slug}) - ID: ${record.id}`);
  }

  // Ensure only the default provider plan has isProviderDefault: true
  await prisma.plan.updateMany({
    where: {
      type: 'provider',
      slug: { not: 'provider-free-default' },
    },
    data: {
      isProviderDefault: false,
    },
  });

  const total = await prisma.plan.count();
  console.log(`[seedPlansPrisma] Successfully seeded ${allPlans.length} plans. Total plans in DB: ${total}`);
}

if (require.main === module) {
  seedPlans()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[seedPlansPrisma] Error:', err);
      process.exit(1);
    });
}

module.exports = { seedPlans, providerPlans, recruiterPlans };
